config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index' #controller#method(vue)
  get "dashboard", to: "pages#dashboard"
  resources :cars, only: [:index, :show] do
    resources :bookings
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_car, only: [:show]

  def index
    @bookings = Booking.all
  end
  
  def show
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    # redirect_to car_booking_path(@car, @booking)
  end
  
  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user
    @booking.total_price = @car.price * (@booking.end_date - @booking.start_date).to_i
    if @booking.save
      redirect_to car_booking_path(@car, @booking)
    else
      render "cars/show"
    end
  end
  
  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :car_id,:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  def index
    @cars = Car.all
    @bookings = Booking.all
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

  def booking_dashboard
    @bookings = Booking.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!

  def home
  end

  def dashboard
    @bookings = Booking.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your booking</h1>
  <p><%= @car.brand %> <%= @car.model %></p>
  <p>From <%= @booking.start_date %> to <%= @booking.end_date %></p>
  <!-- <p>For <%= @car.price * (@booking.end_date - @booking.start_date).to_i %></p>%> -->
  <p> Total of your reservation : <%= @booking.total_price %>€</p>
  <p><%= link_to "Home", root_path , class: "button-blue"%>
    <%= link_to "See all my reservations", dashboard_path, class: "button-blue" %>
  </p>

  
</div>

app/views/cars/booking_dashboard.html.erb
<div class="container">
  <h1>Your reservations</h1>
  
</div>

app/views/cars/index.html.erb
<div class = "container">
  <h1>Our Cars</h1>
  
  <div class = "Cars">
    <h2>Choose the car you want to book</h2>
  </div>
  
  <div class="select-car">
    <ul class="list-car text-align" ><% @cars.each do |car|%>
          <%= image_tag car.car_picture, class: "image-car", width: 400 %>
          <h1><%= car.brand %> <%= car.model %></h1>
          <p><%= car.price %>€ per day</p>
          <p><%= link_to "See", car_path(car), class: "button-blue" %></p>
        <% end %> 
    <ul>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h1>Choose your period of rental</h1>

  <ul>
    <p><%= image_tag @car.car_picture, width: 400 %></p>
    <h1><%= @car.brand %> <%= @car.model %></h1>
    <p><%= @car.price %>€ per day</p>
  <ul>

  
    <%= simple_form_for([@car,@booking]) do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "Book", class: "button-blue" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
    <div class="container"></div>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>My dashboard</h1>
  <h2>My reservations</h2>
  <div>
    <% @bookings.each do |booking| %>
      <h1><%= booking.car.brand %>
      <%= booking.car.model %></h1>
      <p><%= booking.start_date %></p>
      <p><%= booking.end_date %></p>
      <p><%= booking.total_price %>€</p>
      <%= link_to "Cancel", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } %>
      <%= link_to "Home", cars_path %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Home</h1>
<p></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>My footer</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="site">
	
	<nav class="nav">
		<div class="nav__title">
      CarBnb
    </div>
		<ul class="nav__list">
      <li class="nav__item"> <%= link_to "home", root_path %> </li>
      <li class="nav__item"> <%= link_to "Dashboard", dashboard_path %> </li>
			<li class="nav__item" > <% if user_signed_in? %>
          <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete %>
          <%= image_tag "https://api.iconify.design/emojione-monotone/person-bowing.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= link_to "Me connecter", new_user_session_path %>
        <% end %>
      </li>
		</ul>
	</nav>
</div>